name: recyclick
description: "Aplicativo ecológico"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Ícones padrão do iOS
  cupertino_icons: ^1.0.8

  # Internacionalização (formatos de datas, números etc.)
  intl: ^0.18.1

  # Firebase Core e autenticação com e-mail/senha e Google
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.1.6

  # Câmera e Reconhecimento de Imagens com ML Kit
  camera: ^0.11.1
  google_mlkit_image_labeling: ^0.14.1

  # Mapas e geolocalização
  google_maps_flutter: ^2.5.2
  geolocator: ^14.0.1
  geocoding: ^2.1.0
  permission_handler: ^12.0.0+1

  # Armazenamento local com Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # Compartilhamento de conteúdo
  share_plus: ^7.2.1

  # 🔔 Notificações locais com versão personalizada (local)
  flutter_local_notifications:
    path: flutter_local_notifications_custom/

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints e ferramentas de análise
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

  # Geração de adapters para Hive
  hive_generator: ^2.0.1

  # Versão compatível do analyzer para Hive Generator
  analyzer: ^6.11.0

flutter:
  uses-material-design: true

  # Diretório de assets do app (imagens, ícones, etc.)
  assets:
    - assets/
